- name: Demo on Variables
  hosts: localhost
  vars: #vaiable
    URL: kiran.com  #intialize the kiran.com in URL variable
  tasks:
    - name: Print URL variable
      ansible.builtin.debug: #it's used to print the variable
        msg: "{{ URL }}"

#Value starts a variable, like msg:{{ URL }} then quotes are needed, if it does not start with variable like msg: Hello {{ URL }}, then quotes are npt needed.

- name: Demo on Task Variables
  hosts: localhost
  vars:
    URL1: sample.com
    URL2: sample.com
  tasks:
    - name: Print URL1 variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
      vars:
        URL1: kiran.com
    - name: Print URL2 variable
      ansible.builtin.debug:
        msg: "{{ URL2 }}"
      vars:
        URL2: kiran.com

#How to execute shell command in ansible
#command is uptime
- name: register Variable Example
  hosts: localhost
  tasks:
    - name: get Uptime of server
      ansible.builtin.shell: uptime
      register: OUT
    - name: Print OUT var
      ansible.builtin.debug:
        msg: "{{ OUT }}"