- name: Demo On condition
  hosts: localhost
  tasks:
    - name: Print Lnux
      ansible.builtin.debug:
        msg: Hello, Linux
      when os_name: "Linux"

    - name: Print Unix
      ansible.builtin.debug:
        msg: Print Unix
      when os_name: "Unix"