# loop is used to run the same task again and again using different inputs
- name: demo on Loops
  hosts: localhost
  tasks:
    - name: Loop
      ansible.builtin.debug:
        msg: fruit - {{ item }} # item is bydeafult variable in ansible
      loop:
        - apple
        - orange
        - banana

- name: Demo on loop
  hosts: localhost
  vars:
    fruites:
      - apple
      - banana
      - orange
  tasks:
    - name: Loop
      ansible.builtin.debug:
        msg: fruit - {{ item }}
      loop: "{{fruites}}"

#How to use map in the ansible
- name: Demo on loops -map
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - orrange
  tasks:
    - name: Loop
      ansible.builtin.debug:
        msg: fruit name - {{ item.name }}, quantity - {{ item.quantity }}
      loop:
        - { name: "apple", quantity: 100}
        - {name: "banana", quantity: 200}
        - {name: "orrange", quantity: 300}
