- name: Demo on error handling
  hosts: localhost
  tasks:
    - name: execute ls command
      ansible.builtin.shell: lss
      #ignore_errors: yes
    - name: print hello
      ansible.builtin.debug:
        msg: Hello