- name: Demo on error handling
  hosts: localhost
  tasks:
    - name: execute ls command
      ansible.builtin.shell: lss
      ignore_errors: yes #it is used for error handling when we use this command it will ignore the error and proceed the further process
    - name: print hello
      ansible.builtin.debug:
        msg: Hello