- name: demo on Filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT #store the values in OUT variable
    - name: Print No of Users logged in
      ansible.builtin.debug:
        msg: "{{ OUT }}"

 #How do we use filter check bellow example :-
- name: Demo on Filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
    - name: Print No of users logged in
      ansible.builtin.debug:
        msg: "{{ OUT.stdout | split (',') }}"

#I want to print the user list by giving index means when we give 0 it display index 0 value and 1 it display the index 1 value.
- name: Demo on Filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
    - name: Print No of users logged in
      ansible.builtin.debug:
        msg: "{{ (OUT.stdout | split (','))[1] }}"

# I want to print only number not use then u can follow bellow one
- name: Demo on Filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
    - name: Print No of users logged in
      ansible.builtin.debug:
        msg: "{{ (OUT.stdout | split (','))[1] | split(' ')}}"
# continue I want to print only number not use then u can follow bellow one
- name: Demo on Filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
    - name: Print No of users logged in
      ansible.builtin.debug:
        msg: "{{ ((OUT.stdout | split (','))[1] | split(' '))[2]}}"

#above code given me output in double quotes mean string value but i wanted to come this as a integer please follow bellow one
- name: Demo on Filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
    - name: Print No of users logged in
      ansible.builtin.debug:
        msg: "{{ ((OUT.stdout | split (','))[1] | split(' '))[2]}}"

