- name: Demo on loop
  hosts: localhost
  tasks:
    - name: loop
      ansible.builtin.debug:
        msg: fruit - {{ item }}
      loop:
        - banana
        - chikku
        - dragan

- name: Demo on loop
  hosts: localhost
  vars:
    Animals:
      - Cow
      - Dog
      - Tiger
  tasks:
    - name: demo
      ansible.builtin.debug:
        msg: animals - {{ item }}
      loop: " {{Animals}}"