- name: Demo on variable
  hosts: all
  vars:
    URL: kirangowda
  tasks:
    - name: print the variable
      ansible.builtin.debug:
        msg: " {{ URL }}"

#--------
- name: Declare variable at task level
  hosts: all
  tasks:
    - name: print var one
      ansible.builtin.debug:
        msg: " {{ URL1 }}"
      vars:
        URL1: kiru
    - name: print var two
      ansible.built.debug:
        msg: " {{ URL2 }}"
      vars:
        URL2: Gowda