- name: sample
  hosts: localhost
  vars:
    LUCK: kiran.com
    LUCK1: kiran.com
  tasks:
    - name: Ping
      ansible.builtin.debug:
        msg: " {{ LUCK }} "
      vars:
        LUCK: abhi.com
    - name: print
      ansible.builtin.debug:
        msg: " {{ LUCK1 }} "
      vars:
        LUCK1: abhi.com
